### ISSUE TITLE
'Wire1' was not declared in this scope

### ISSUE THREAD

**Issue by harry1329** [sparkfun/SparkFun_LIS2DH12_Arduino_Library#1]
Hello I'm Wonhyuck.

I tried to compile the example 'Example1_BasicReadings', but it shows a compile error.

And it says 'Wire1' was not declared in this scope.

I Googled it, and some people said that re-install esp32 in board manager, but it doesn't work.

I tried to find Wire1 in Wire library, but I couldn't find it.

How can I solve this problem?

I'm using the newest arduino  IDE and MEGA 2560 board.

Thank you very much!

**Comment by nseidle** [comment]
I've re-written the examples to use Wire instead of Wire1. This should fix your issue.
