### ISSUE TITLE
Not possible to read acceleration data with a frequency of approx. 5 kHz.

### ISSUE THREAD

**Issue by mraugit** [sparkfun/SparkFun_LIS2DH12_Arduino_Library#2]
It is not possible to read acceleration data with a frequency of approx. 5 kHz.

Workbench:
Development board: Sparkfun edge
Library Version 1.0.0 (Version from Arduino IDE)
Powered by USB?

Steps to reproduce:
I use the Example: Example1_BasicReadings with the following modifications:
1. Change Wire to Wire1
2. Disable temperature
3. Disable tab detection
3. Set data rate to LIS2DH12_ODR_5kHz376_LP_1kHz344_NM_HP
4. Print last read value only every 1000 captured values.

### Expected behavior
I expect to get approx. five outputs every second 

### Actual behavior
The max. frequence is about 500Hz

**Comment by nseidle** [comment]
Neat. It's probably limited by I2C comm at 1MHz. I just tried it and got up to about 900Hz:

![image](https://user-images.githubusercontent.com/117102/72026108-986b9980-3237-11ea-9a8e-52ad95cd8790.png)

The serial buffer is getting corrupt but I can get to ~911Hz. I added example 8 to the lib so you can see what I did:

* Wire.setClock(1000000);
* Increase serial to 500kbps (but I like your solution better of just counting, not outputting)

Oh, and we've got a 1ms delay inside **SPARKFUN_LIS2DH12::waitForNewData()**. Removing the delay doesn't seem to help. We're polling where if you're really trying to hit 5k, you'd probably need:

* SPI (maybe)
* Interrupts

**Comment by mraugit** [comment]
Thank you for checking. I definitely need the 5 kHz sampling rate. However, I fear that my knowledge is not sufficient to extend the library with SPI and interrupt communication.

**Comment by nseidle** [comment]
We don't plan to support SPI anytime soon but we welcome a PR. It looks like this accel and library are going to be limited to ~1kHz for now.
