### ISSUE TITLE
Activating INT1 using single click

### ISSUE THREAD

**Issue by DylanGWork** [sparkfun/SparkFun_LIS2DH12_Arduino_Library#5]
Setting up the Tap function to use INT1 to wake-up the MCU.

Following the datasheet, or the LIS2DH12 manufacturers github, I cannot find a way to activate INT1 (or INT2) when a tap is activated.
https://www.st.com/resource/en/datasheet/lis2dh12.pdf
https://github.com/STMicroelectronics/lis2dh12

This seems like a very obvious requirement from this accelerometer, I'm hoping it exists and I've just managed to miss it.

I have a custom board and set-up using an ESP32, we've checked that interrupts are working by setting up INT1 by the methods already available and checked that the current method of checking when a tap is activated works, we don't believe we have any hardware issues. 

Expected behaviour 
INT1 Pin goes high when a tap is detected. Enabling a tap to wake the ESP32 from deepsleep.

Actual behavior
Need to be checking the registers to see if there has been a tap, very ineffective for low power usage.

Cheers,
Dylan

**Comment by nseidle** [comment]
See [this commit](https://github.com/sparkfun/SparkFun_LIS2DH12_Arduino_Library/commit/976484164da8489a8d97c30b80520cf56461a91d). We added Int1 support. I used these functions to do something similar: turn on a power circuit, but it should do what you need.

**Comment by DylanGWork** [comment]
That is fantastic, thank you for the help.

I've added the modifications, do you have an example of how you set this up? 

Through multiple attempts of other solutions, I may have changed a few things around in a different order of implementation, unsure if that changes things.

Cheers,
Dylan

**Comment by fafiunal** [comment]
@DylanGWork Hi my friend.

I am working about a similar application for wake the ESP32 deep slep. Do you success for this app.? if successi may you share with me?

**Comment by nseidle** [comment]
I've added a tap example. It's not great, but it works.
